runtime: nodejs20 # specify your Node.js version
env: standard
instance_class: F1 # instance class (F1 is the smallest and least expensive)

automatic_scaling:
  max_instances: 1 # limit to control cost

network: {}
